spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres_tuke?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect
#rsa.private-key=classpath:certs/private.pem
#rsa.public-key=classpath:certs/public.pem
#jwt.secret=s0eX10Mk1ugaZGk8SJLY
#jwt.token.expirationInMS=300000
#spring.main.allow-circular-references=true
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
jwt.token.expirationInMS=300000
jwt.secret=VTVrL1FmTGRoVnFja2RTcGEza09lbm1YY0w1RW1OUndvZDNhUC80Sy9OND0=
#spring.main.allow-circular-references=true

# spring.main.allow-circular-references=true  je len docasne riesenie na problem  circular z�vislos?i medzi beanami (JwtAuthenticationFilter, UserServiceImpl, JwtConfig)


